language: php
php:
  - '7.1'

notifications:
  email:
    recipients:
      - dean@g3d-development.com
    on_success: never # default: change
    on_failure: always # default: always

script: phpunit tests
